#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh xbr_5x_vs.h /Tvs_3_0 5xBR-v3.5.cg /Exbr5x_vs_main
//
//
// Parameters:
//
//   float2 settings_texture_size;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   settings_texture_size c0       1
//

// Shader type: vertex 

xvs_3_0
defconst settings_texture_size, float, vector, [1, 2], c0
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=2
config VsResource=1
// VsExportCount=2

dcl_index r0.x
dcl_texcoord o0.xy
dcl_texcoord1 o1
dcl_color o2


    exec
    vfetch r2, r0.x, position
    vfetch r1, r0.x, color
    vfetch r0.xy__, r0.x, texcoord
    alloc position
    exec
    mov oPos, r2
    alloc interpolators
    exece
    rcp o1.x000, c0.x
    rcp o1.w, c0.y
    mov o0.xy, r0.xy
    mov o2, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_xbr5x_vs_main[] =
{
    0x102a1101, 0x000000e4, 0x00000090, 0x00000000, 0x00000024, 0x00000000, 
    0x00000094, 0x00000000, 0x00000000, 0x0000006c, 0x0000001c, 0x0000005f, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000058, 0x00000030, 
    0x00020000, 0x00010000, 0x00000048, 0x00000000, 0x73657474, 0x696e6773, 
    0x5f746578, 0x74757265, 0x5f73697a, 0x6500abab, 0x00010003, 0x00010002, 
    0x00010000, 0x00000000, 0x76735f33, 0x5f300032, 0x2e302e32, 0x30333533, 
    0x2e3000ab, 0x00000000, 0x00000090, 0x00210002, 0x00000000, 0x00000000, 
    0x00002863, 0x00000001, 0x00000003, 0x00000004, 0x00000290, 0x00100003, 
    0x0000a004, 0x00305005, 0x00003050, 0x0001f151, 0x0003f2a0, 0x00001009, 
    0x00000007, 0x00001008, 0x0000100a, 0x70153003, 0x00001200, 0xc2000000, 
    0x00001006, 0x00001200, 0xc4000000, 0x00004007, 0x00002200, 0x00000000, 
    0x05f82000, 0x00000688, 0x00000000, 0x05f81000, 0x00000688, 0x00000000, 
    0x05f80000, 0x00000fc8, 0x00000000, 0xc80f803e, 0x00000000, 0xe2020200, 
    0x4c10c001, 0x0000006c, 0xc2000000, 0x4c808001, 0x000000b1, 0xc2000000, 
    0xc8038000, 0x00b0b000, 0xe2000000, 0xc80f8002, 0x00000000, 0xe2010100, 
    0x00000000, 0x00000000, 0x00000000
};
