#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh xbr_5x_crt_ps.h /Tps_3_0 5xBR-v3.5+CRT.cg /Exbr5xcrt_ps_main
//
//
// Parameters:
//
//   sampler2D decal;
//   float2 settings_texture_size;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   settings_texture_size c0       1
//   decal                 s0       1
//

// Shader type: pixel 

xps_3_0
defconst decal, sampler2d, object, [1, 1], s0
defconst settings_texture_size, float, vector, [1, 2], c0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=16
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_texcoord1 r1
dcl_color_centroid r2

def c252, 2.4000001, 0.454545468, 0, 0
def c253, -0.5, 0.5, 4, 0
def c254, 1, 2, 1.5, 1.45000005
def c255, 5.47200012, 14.3520002, 28.1760006, -1


    exec
    mad r5, r1, c254.y, r0.xyxy
    dp3 r2.y, r1.zx, c254.x
    dp3 r2.z, r1.wy, c254.x
    add r3, r0.xyxy, r1
    add r12, r0.xyxy, -r1.zwxy
    add r10.xy, r3.xy, -r1.zw
  + movs r2._, r12.z
    exec
    add r6.xy, r3.xy, r1.zw
  + adds_prev r2.x, r1.z
    add r0.zw, r6.xxxy, r1.zzzw
  + movs r2._, r12.w
    add r9.xy, r0.xy, r2.yz
  + adds_prev r2.y, r1.w
    tfetch2D r4.xyz_, r2.xy, tf0
    tfetch2D r7.xyz_, r3.xy, tf0
    tfetch2D r8.xyz_, r0.xy, tf0
    exec
    tfetch2D r15.xyz_, r12.zw, tf0
    tfetch2D r2.xyz_, r5.zw, tf0
    tfetch2D r5.xyz_, r5.xy, tf0
    tfetch2D r6.xyz_, r6.xy, tf0
    tfetch2D r9.xyz_, r9.xy, tf0
    tfetch2D r10._xyz, r10.xy, tf0
    exec
    tfetch2D r11.xyz_, r0.zw, tf0
    tfetch2D r1.xyz_, r12.xy, tf0
    tfetch2D r3.xyz_, r3.zw, tf0
    alloc colors
    exec
    dp3 r16.z, r3.zxy, c255.xyz
    dp3 r16.w, r1.zxy, c255.xyz
    dp3 r10.x, r11.zxy, c255.xyz
    dp3 r10.y, r10.wyz, c255.xyz
    dp3 r10.w, r9.zxy, c255.xyz
    dp3 r0.z, r6.zxy, c255.xyz
    exec
    dp3 r5.x, r5.zxy, c255.xyz
    dp3 r5.y, r2.zxy, c255.xyz
  + movs r2._, r0.y
    dp3 r0.w, r15.zxy, c255.xyz
  + muls_prev r2.y, c0.y
    dp3 r16.y, r8.zxy, c255.xyz
  + movs r2._, r0.x
    dp3 r16.x, r7.zxy, c255.xyz
  + muls_prev r2.x, c0.x
    frc r2.x, r2.x
  + frcs r2.z, r2.y
    exec
    add r12.x, -r16_abs.x, r16_abs.y
  + mulsc r9.x, c253.y, r2.x
    dp3 r10.z, r4.zxy, c255.xyz
  + addsc r2.y, c253.x, r2.z
    sne r14.y, r0_abs.w, r10_abs.z
  + addsc r0.y, c253.y, r2.z
    cndge r4.xyz, -r2.y, r1.zxy, r3.zxy
    add r13.yw, r0_abs.z, -r5_abs.yyx
  + subsc r0.x, c254.x, r2.y
    add r5, r16_abs.zyxy, -r16_abs.xzw
  + movs r2._, r16_abs.x
    exec
    add r12.yzw, -r0_abs.wwzw, r16_abs.yyyz
  + adds_prev r13.z, -r10_abs.z
    add r6, r16_abs.yyz, -r10_abs.zyxy
  + movs r2._, r16_abs.x
    sne r11.xy, r16_abs.y, r16_abs.xz
  + adds_prev r13.x, -r10_abs.w
    mul r2.w, r5_abs.x, c253.z
  + adds r0.z, r13_abs.zz
    sne r14.xzw, r16_abs.wy, r10_abs.yzzy
  + movs r2._, r12_abs.w
    add r9.zw, r6_abs.yyyw, r6_abs.xxxw
  + adds_prev r9.y, r6_abs.z
    exec
    cndge r2.y, -r2.y, r0.y, r0.x
    sge r10.x, r6_abs.w, r0.z
  + adds r2.y, r2.yy
    sge r10.y, r13_abs.z, r9.w
  + movs r2._, r14.z
    sge r6.xw, r12_abs.xy, r5_abs.wy
  + muls_prev r5.x, r14.y
    sge r0.xw, r5_abs.yw, r12_abs.xy
  + movs r2._, r14.w
    cndgt r0.xyz, r0.x, r7.xyz, r3.xyz
    exec
    cndgt r6.xyz, r6.x, r1.xyz, r7.xyz
    cndgt r7.xyz, r0.w, r15.xyz, r1.xyz
    cndgt r3.xyz, r6.w, r3.xyz, r15.xyz
    add r1.xy, r9.yz, r13_abs.xy
  + muls_prev r5.y, r14.x
    min r2.y, r2.y, c254.x
  + movs r2._, r1.y
    mad r11.z, -r2.y, r2.y, c254.x
    exec
    add r0.w, r1.x, r5_abs.z
  + adds_prev r2.y, r13_abs.w
    mad r0.w, r12_abs.z, c253.z, r0.w
    add r9.yw, r2.xxy, r2.xxw
  + muls r5.z, r11.xy
    sgt r10.z, r0.w, r9.w
  + muls r5.w, r11.zz
    sne r1.yzw, r5.xxyz, c253.w
  + addsc r9.z, c255.w, r2.z
    add r9.xyw, r9.xyz, r2.z
    exec
    mad r1.x, -r9.w, r9.w, c254.x
    mul r1.yzw, r10.xxyz, r1.yyzw
  + movs r2._, r2.z
    sne r1.yzw, r1.yyzw, c253.w
  + adds_prev r9.z, r2.x
    sgt r2.xyz, r9.xyz, c254.xyz
    mul r9.xy, r2.xy, r1.yz
    sne r2.xy, r9.xy, c253.w
    exec
    add r2.z, r2.z, r2.x
    snes r2.z, r2.z
    add r2.x, r2.z, r2.y
  + log r1.y, r4_abs.y
    sne r2.x, r2.x, c253.w
  + log r1.z, r4_abs.z
    mul r2.w, r1.w, r2.x
  + log r1.w, r4_abs.x
    cndeq r2.xyz, r2.w, r8.xyz, r3.xyz
    exec
    cndeq r2.xyz, r2.w, r2.xyz, r7.xyz
    cndeq r2.xyz, r2.w, r2.xyz, r6.xyz
    cndeq r2.xyz, r2.w, r2.yzx, r0.yzx
    log r0.x, r2_abs.x
    log r0.y, r2_abs.y
    mul r2.xyw, r1.yzw, c252.x
  + log r0.z, r2_abs.z
    exec
    mul r0.yzw, r0.zzxy, c252.x
  + exp r0.x, r2.x
    exp r1.y, r0.y
    exp r1.z, r0.z
    exp r1.w, r0.w
    mul r0.zw, r1.x, r1.yyyx
  + exp r0.y, r2.y
    mul r2.xyz, r0.zw, r1.xzw
  + exp r0.z, r2.w
    exec
    mad r2.xyz, r5.w, r0.xyz, r2.xyz
    mul r2.xyz, r2.xyz, c254.w
    log r2.x, r2_abs.x
    log r2.y, r2_abs.y
    log r2.z, r2_abs.z
    mul r2.xyz, r2.xyz, c252.y
    exece
    exp_sat oC0.x001, r2.x
    exp_sat oC0.y, r2.y
    exp_sat oC0.z, r2.z

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_xbr5xcrt_ps_main[] =
{
    0x102a1100, 0x00000114, 0x00000538, 0x00000000, 0x00000024, 0x000000c0, 
    0x000000e8, 0x00000000, 0x00000000, 0x00000098, 0x0000001c, 0x0000008b, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000084, 0x00000044, 
    0x00030000, 0x00010000, 0x0000004c, 0x00000000, 0x0000005c, 0x00020000, 
    0x00010000, 0x00000074, 0x00000000, 0x64656361, 0x6c00abab, 0x0004000c, 
    0x00010001, 0x00010000, 0x00000000, 0x73657474, 0x696e6773, 0x5f746578, 
    0x74757265, 0x5f73697a, 0x6500abab, 0x00010003, 0x00010002, 0x00010000, 
    0x00000000, 0x70735f33, 0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 
    0x00000000, 0x00000001, 0x00000000, 0x00000000, 0x00000014, 0x01fc0010, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000040, 0x000004f8, 
    0x10001000, 0x00000008, 0x00000000, 0x00002863, 0x00030007, 0x00000001, 
    0x00003050, 0x0000f151, 0x0000f2a0, 0x4019999a, 0x3ee8ba2f, 0x00000000, 
    0x00000000, 0xbf000000, 0x3f000000, 0x40800000, 0x00000000, 0x3f800000, 
    0x40000000, 0x3fc00000, 0x3fb9999a, 0x40af1aa0, 0x4165a1cb, 0x41e16873, 
    0xbf800000, 0x00006009, 0x600f1200, 0x12000540, 0x05556015, 0x301b1200, 
    0x12000015, 0x00000000, 0x601ec400, 0x12000000, 0x00006024, 0x602a1200, 
    0x12000000, 0x00006030, 0x60361200, 0x12000000, 0x0000603c, 0x60421200, 
    0x12000000, 0x00006048, 0x604e1200, 0x12000000, 0x00006054, 0x605a1200, 
    0x12000000, 0x00006060, 0x30661200, 0x22000000, 0xc80f0205, 0x0000b1a0, 
    0xab01fe00, 0xc8020202, 0x006e6c00, 0xb001fe00, 0xc8040202, 0x00b36c00, 
    0xb001fe00, 0xc80f0203, 0x00a00000, 0xe0000100, 0xc80f020c, 0x02a0aa00, 
    0xe0000100, 0x1403020a, 0x02b01ac6, 0xe003010c, 0x04130206, 0x00b01ac6, 
    0xe0030101, 0x140c0200, 0x00ac061b, 0xe006010c, 0x04230209, 0x00b0c51b, 
    0xe0000201, 0x10084041, 0x1f1ffe88, 0x00004000, 0x10087061, 0x1f1ffe88, 
    0x00004000, 0x10088001, 0x1f1ffe88, 0x00004000, 0xb808f181, 0x1f1ffe88, 
    0x00004000, 0xb80820a1, 0x1f1ffe88, 0x00004000, 0x100850a1, 0x1f1ffe88, 
    0x00004000, 0x100860c1, 0x1f1ffe88, 0x00004000, 0x10089121, 0x1f1ffe88, 
    0x00004000, 0x1008a141, 0x1f1ff447, 0x00004000, 0xb808b001, 0x1f1ffe88, 
    0x00004000, 0x10081181, 0x1f1ffe88, 0x00004000, 0xb8083061, 0x1f1ffe88, 
    0x00004000, 0xc8040210, 0x00bec000, 0xb003ff00, 0xc8080210, 0x00bec000, 
    0xb001ff00, 0xc801020a, 0x00bec000, 0xb00bff00, 0xc802020a, 0x00c3c000, 
    0xb00aff00, 0xc808020a, 0x00bec000, 0xb009ff00, 0xc8040200, 0x00bec000, 
    0xb006ff00, 0xc8010205, 0x00bec000, 0xb005ff00, 0x14020205, 0x00bec0b1, 
    0xb002ff00, 0x0c280200, 0x00bec0b1, 0x900fff00, 0x14020210, 0x00bec06c, 
    0xb008ff00, 0x0c110210, 0x00bec06c, 0x9007ff00, 0x2c410202, 0x006c00b1, 
    0xe8020002, 0xa811090c, 0x046cb180, 0xe09090fd, 0xb024020a, 0x00bec042, 
    0xb004fffd, 0xb022000e, 0x001bc682, 0xe7808afd, 0xc8070204, 0x04b1bebe, 
    0xed020103, 0xb81a000d, 0x02c66141, 0xe08085fe, 0x140f0205, 0x02a2146c, 
    0xe0909090, 0x044e0d0c, 0x050bf1c6, 0xe080908a, 0x140f0206, 0x02c1a26c, 
    0xe0908a90, 0x04130d0b, 0x01b1c41b, 0xe790908a, 0x00480002, 0x006cc6c6, 
    0xa185fd8d, 0x140d020e, 0x00b3851b, 0xe7908a8c, 0x042c0909, 0x00312cc6, 
    0xe0868686, 0xc8020202, 0x04b1b16c, 0xed020000, 0x0021020a, 0x001bc6b1, 
    0xe6860002, 0x1402020a, 0x00c61bc6, 0xe68d090e, 0x0c190506, 0x00b0b3b1, 
    0xe68c850e, 0x14090200, 0x0019b01b, 0xe6858c0e, 0xc8070200, 0x006cc0c0, 
    0xee000703, 0xc8070206, 0x006cc0c0, 0xee060107, 0xc8070207, 0x001bc0c0, 
    0xee000f01, 0xc8070203, 0x001bc0c0, 0xee06030f, 0x0c230501, 0x00c5b06c, 
    0xe0098d0e, 0x14020202, 0x00b16cb1, 0xa302fe01, 0xc804020b, 0x04b1b16c, 
    0xcb0202fe, 0x04280200, 0x006cc61b, 0xe001858d, 0xc8080200, 0x00c6c61b, 
    0xab8cfd00, 0x084a0509, 0x00bc1c61, 0xe002020b, 0x0884050a, 0x001b1bc6, 
    0xe500090b, 0xb04e0901, 0x00fc1b02, 0xa705fdff, 0xc80b0209, 0x00c0c600, 
    0xe0090200, 0xc8010201, 0x041b1b6c, 0xcb0909fe, 0x140e0201, 0x00fc01c6, 
    0xe10a0102, 0x044e0901, 0x00011b6c, 0xa701fd02, 0xc8070202, 0x00c0c000, 
    0xa509fe00, 0xc8030209, 0x00b0c500, 0xe1020100, 0xc8030202, 0x00b01b00, 
    0xa709fd00, 0xc8040202, 0x00c66c00, 0xe0020200, 0x28400202, 0x000000c6, 
    0xe2020202, 0x40210102, 0x00c6b1b1, 0xe0020284, 0x40410102, 0x006c1bc6, 
    0xa702fd84, 0x40880102, 0x001b6c6c, 0xe1010284, 0xc8070202, 0x001bc0c0, 
    0xec020803, 0xc8070202, 0x001bc0c0, 0xec020207, 0xc8070202, 0x001bc0c0, 
    0xec020206, 0xc8070202, 0x001b6565, 0xec020200, 0x40100002, 0x0000006c, 
    0xe2020282, 0x40200002, 0x000000b1, 0xe2020282, 0x404b0002, 0x00156cc6, 
    0xa101fc82, 0x381e0000, 0x00a66c6c, 0xa100fc02, 0x38200102, 0x000000b1, 
    0xe2020200, 0x38400102, 0x000000c6, 0xe2020200, 0x38800102, 0x0000001b, 
    0xe2020200, 0x382c0000, 0x006c71b1, 0xe1010102, 0x38470002, 0x001a141b, 
    0xe1000102, 0xc8070202, 0x001bc0c0, 0xeb050002, 0xc8070202, 0x00c01b00, 
    0xa102fe00, 0x40100202, 0x0000006c, 0xe2020282, 0x40200202, 0x000000b1, 
    0xe2020282, 0x40400202, 0x000000c6, 0xe2020282, 0xc8070202, 0x00c0b100, 
    0xa102fc00, 0x3a98c000, 0x0000006c, 0xe2020202, 0x3a208000, 0x000000b1, 
    0xe2020202, 0x3a408000, 0x000000c6, 0xe2020202, 0x00000000, 0x00000000, 
    0x00000000
};
