#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh xbr_5x_ps.h /Tps_3_0 5xBR-v3.5.cg /Exbr5x_ps_main
//
//
// Parameters:
//
//   sampler2D decal;
//   float2 settings_texture_size;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   settings_texture_size c0       1
//   decal                 s0       1
//

// Shader type: pixel 

xps_3_0
defconst decal, sampler2d, object, [1, 1], s0
defconst settings_texture_size, float, vector, [1, 2], c0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=13
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_texcoord1 r1
dcl_color_centroid r2

def c252, 0, 0, 0, 0
def c253, 5.47200012, 14.3520002, 28.1760006, 0
def c254, 1.5, 1, 2, 0.5
def c255, 4, 0, 0, 0


    exec
    mad r8, r1, c254.z, r0.xyxy
    dp3 r3.x, r1.zx, c254.y
    dp3 r3.y, r1.wy, c254.y
    add r2, r0.xyxy, -r1
    add r10, r0.xyxy, r1.zwxy
    add r0.zw, r2.xxxy, r1.zzzw
  + movs r2._, r10.z
    exec
    add r3.zw, r10.zzzw, r1.zzzw
  + adds_prev r9.x, -r1.z
    add r3.xy, r0.xy, r3.xy
  + movs r2._, r10.w
    add r4.xy, r3.zw, r1.zw
  + adds_prev r9.y, -r1.w
    tfetch2D r5.xyz_, r4.xy, tf0
    tfetch2D r6.xyz_, r3.zw, tf0
    tfetch2D r4.xyz_, r0.xy, tf0
    exec
    tfetch2D r7.xyz_, r3.xy, tf0
    tfetch2D r11.xyz_, r10.zw, tf0
    tfetch2D r1.xyz_, r2.zw, tf0
    tfetch2D r3.xyz_, r2.xy, tf0
    tfetch2D r2._xyz, r8.xy, tf0
    tfetch2D r8.xyz_, r8.zw, tf0
    exec
    tfetch2D r10.xyz_, r10.xy, tf0
    tfetch2D r9.xyz_, r9.xy, tf0
    tfetch2D r12.xyz_, r0.zw, tf0
    alloc colors
    exec
    dp3 r12.y, r12.zxy, c253.xyz
    dp3 r12.z, r9.zxy, c253.xyz
    dp3 r12.w, r10.zxy, c253.xyz
    dp3 r2.x, r8.zxy, c253.xyz
    dp3 r2.y, r2.wyz, c253.xyz
    dp3 r13.y, r3.zxy, c253.xyz
    exec
    dp3 r13.z, r1.zxy, c253.xyz
  + movs r2._, r0.y
    dp3 r12.x, r11.zxy, c253.xyz
  + muls_prev r0.z, c0.y
    dp3 r2.w, r7.zxy, c253.xyz
  + movs r2._, r0.x
    dp3 r13.x, r4.zxy, c253.xyz
  + muls_prev r0.y, c0.x
    dp3 r2.z, r6.zxy, c253.xyz
  + frcs r0.x, r0.z
    add r8.x, r13_abs.x, -r2_abs.z
  + frcs r0.y, r0.y
    exec
    dp3 r13.w, r5.zxy, c253.xyz
  + movs r2._, r12_abs.x
    dp3 r6.y, r0.xy, c254.y
  + adds_prev r9.w, -r2_abs.w
    mad r6.xz, r0.yx, c254.wy, r0.xy
    add r5.xy, r2_abs.z, -r2_abs.xy
  + movs r2._, r13_abs.x
    add r9.xyz, r12_abs.xw, -r13_abs.zyw
  + adds_prev r3.w, -r13_abs.y
    add r2, r13_abs.x, -r12_abs.zyxw
  + movs r2._, r13_abs.x
    exec
    sne r7.xyz, r13_abs.x, r12_abs.yxz
  + adds_prev r0.z, -r13_abs.z
    add r8.yzw, r12_abs.wwwx, -r12_abs.xxzy
  + adds r1.w, r2_abs.xy
    sne r0.xyw, r13_abs.xzy, r12_abs.wzy
  + adds r5.z, r8_abs.ww
    sgt r6.xyz, r6.zxy, c254.xyz
  + adds r5.w, r8_abs.zz
    sge r4.w, r3_abs.w, r2_abs.w
  + movs r2._, r7.y
    sge r6.w, r0_abs.z, r3_abs.w
  + muls_prev r3.w, r0.x
    exec
    sge r0.z, r2_abs.z, r0_abs.z
  + movs r2._, r7.z
    sge r2.x, r2_abs.w, r2_abs.z
  + muls_prev r2.w, r0.y
    cndgt r2.xyz, r2.x, r11.xyz, r10.xyz
    cndgt r0.xyz, r0.z, r1.xyz, r11.xyz
    cndgt r1.xyz, r6.w, r3.xyz, r1.xyz
    cndgt r3.xyz, r4.w, r10.xyz, r3.xyz
    exec
    sge r7.yz, r8_abs.zzw, r5.zzw
  + movs r2._, r7.x
    dp4 r5.z, r9_abs, c254.y
  + muls_prev r0.w, r0.w
    add r1.w, r1.w, r5_abs.x
  + snes r5.x, r3.w
    add r5.w, r1.w, r5_abs.y
  + snes r5.y, r0.w
    mad r5.zw, r8_abs.xxxy, c255.x, r5.zzzw
    sgt r7.x, r5.z, r5.w
  + snes r5.z, r2.w
    exec
    mul r5.xyz, r7.xyz, r5.xyz
    sne r5.xyz, r5.xyz, c253.w
    mul r7.xy, r6.yz, r5.yz
    sne r5.yz, r7.xxy, c253.w
    add r2.w, r6.x, r5.y
    snes r2.w, r2.w
    exec
    add r2.w, r2.w, r5.z
    snes r2.w, r2.w
    mul r2.w, r5.x, r2.w
    cndeq r3.xyz, r2.w, r4.xyz, r3.xyz
    cndeq r1.xyz, r2.w, r3.xyz, r1.xyz
    cndeq r0.xyz, r2.w, r1.xyz, r0.xyz
    exece
    cndeq oC0.xyz1, r2.w, r0.xyz, r2.xyz

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_xbr5x_ps_main[] =
{
    0x102a1100, 0x00000114, 0x000003e8, 0x00000000, 0x00000024, 0x000000c0, 
    0x000000e8, 0x00000000, 0x00000000, 0x00000098, 0x0000001c, 0x0000008b, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000084, 0x00000044, 
    0x00030000, 0x00010000, 0x0000004c, 0x00000000, 0x0000005c, 0x00020000, 
    0x00010000, 0x00000074, 0x00000000, 0x64656361, 0x6c00abab, 0x0004000c, 
    0x00010001, 0x00010000, 0x00000000, 0x73657474, 0x696e6773, 0x5f746578, 
    0x74757265, 0x5f73697a, 0x6500abab, 0x00010003, 0x00010002, 0x00010000, 
    0x00000000, 0x70735f33, 0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 
    0x00000000, 0x00000001, 0x00000000, 0x00000000, 0x00000014, 0x01fc0010, 
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000040, 0x000003a8, 
    0x10000d00, 0x00000008, 0x00000000, 0x00002863, 0x00030007, 0x00000001, 
    0x00003050, 0x0000f151, 0x0000f2a0, 0x00000000, 0x00000000, 0x00000000, 
    0x00000000, 0x40af1aa0, 0x4165a1cb, 0x41e16873, 0x00000000, 0x3fc00000, 
    0x3f800000, 0x40000000, 0x3f000000, 0x40800000, 0x00000000, 0x00000000, 
    0x00000000, 0x00006007, 0x600d1200, 0x12000540, 0x05556013, 0x30191200, 
    0x12000015, 0x00000000, 0x601cc400, 0x12000000, 0x00006022, 0x60281200, 
    0x12000000, 0x0000602e, 0x60341200, 0x12000000, 0x0000603a, 0x60401200, 
    0x12000000, 0x00006046, 0x104c1200, 0x22000000, 0xc80f0208, 0x0000c6a0, 
    0xab01fe00, 0xc8010203, 0x006eb100, 0xb001fe00, 0xc8020203, 0x00b3b100, 
    0xb001fe00, 0xc80f0202, 0x02a00000, 0xe0000100, 0xc80f020a, 0x00a0aa00, 
    0xe0000100, 0x140c0200, 0x00ac06c6, 0xe002010a, 0x041c0903, 0x010606c6, 
    0xe00a0101, 0x14030203, 0x00b0b01b, 0xe000030a, 0x04230904, 0x011a1a1b, 
    0xe0030101, 0x10085081, 0x1f1ffe88, 0x00004000, 0xb8086061, 0x1f1ffe88, 
    0x00004000, 0x10084001, 0x1f1ffe88, 0x00004000, 0x10087061, 0x1f1ffe88, 
    0x00004000, 0xb808b141, 0x1f1ffe88, 0x00004000, 0xb8081041, 0x1f1ffe88, 
    0x00004000, 0x10083041, 0x1f1ffe88, 0x00004000, 0x10082101, 0x1f1ff447, 
    0x00004000, 0xb8088101, 0x1f1ffe88, 0x00004000, 0x1008a141, 0x1f1ffe88, 
    0x00004000, 0x10089121, 0x1f1ffe88, 0x00004000, 0xb808c001, 0x1f1ffe88, 
    0x00004000, 0xc802020c, 0x00bec000, 0xb00cfd00, 0xc804020c, 0x00bec000, 
    0xb009fd00, 0xc808020c, 0x00bec000, 0xb00afd00, 0xc8010202, 0x00bec000, 
    0xb008fd00, 0xc8020202, 0x00c3c000, 0xb002fd00, 0xc802020d, 0x00bec000, 
    0xb003fd00, 0x1404020d, 0x00bec0b1, 0xb001fd00, 0x0c41000c, 0x00bec0b1, 
    0x900bfd00, 0x14080202, 0x00bec06c, 0xb007fd00, 0x0c21000d, 0x00bec06c, 
    0x9004fd00, 0x2c140002, 0x00bec0c6, 0xb006fd00, 0x2c210008, 0x026cc6b1, 
    0xe08d8200, 0x1408020d, 0x00bec06c, 0xb005fd8c, 0x04820906, 0x01b0b11b, 
    0xb000fe82, 0xc8050206, 0x006db3b0, 0xab00fe00, 0x14030205, 0x02c6b06c, 
    0xe082828d, 0x04870309, 0x031812b1, 0xe08c8d8d, 0x140f0202, 0x026c226c, 
    0xe08d8c8d, 0x04470007, 0x016ccdc6, 0xe78d8c8d, 0x008e0108, 0x025b8c61, 
    0xe08c8c82, 0x004b0500, 0x00b4b71b, 0xe78d8c88, 0x00870506, 0x00bec0c6, 
    0xa506fe88, 0x14080204, 0x001b1bb1, 0xe6838207, 0x0c880306, 0x00c61b6c, 
    0xe6808300, 0x14040200, 0x00c6c6c6, 0xe6828007, 0x0c810202, 0x001bc6b1, 
    0xe6828200, 0xc8070202, 0x006cc0c0, 0xee020b0a, 0xc8070200, 0x00c6c0c0, 
    0xee00010b, 0xc8070201, 0x001bc0c0, 0xee060301, 0xc8070203, 0x001bc0c0, 
    0xee040a03, 0x14060207, 0x0016166c, 0xe6880507, 0x0c840005, 0x0000b11b, 
    0xaf89fe00, 0x28180501, 0x001b6c1b, 0xe0018503, 0x28280505, 0x001bb11b, 
    0xe0018500, 0xc80c0205, 0x00ac6c06, 0xab88ff05, 0x28410507, 0x00c61b1b, 
    0xe5050502, 0xc8070205, 0x00c0c000, 0xe1070500, 0xc8070205, 0x00c01b00, 
    0xa705fd00, 0xc8030207, 0x00c5c500, 0xe1060500, 0xc8060205, 0x00bc1b00, 
    0xa707fd00, 0xc8080202, 0x006cb100, 0xe0060500, 0x28800202, 0x0000001b, 
    0xe2020202, 0xc8080202, 0x001bc600, 0xe0020500, 0x28800202, 0x0000001b, 
    0xe2020202, 0xc8080202, 0x006c1b00, 0xe1050200, 0xc8070203, 0x001bc0c0, 
    0xec020403, 0xc8070201, 0x001bc0c0, 0xec020301, 0xc8070200, 0x001bc0c0, 
    0xec020100, 0xc88fc000, 0x001bc0c0, 0xec020002, 0x00000000, 0x00000000, 
    0x00000000
};
